name: flutter_connectivity_auth_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^2.3.0
  battery_plus: ^3.0.4
  shared_preferences: ^2.0.13
  firebase_core: ^2.4.1
  firebase_auth: ^4.3.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
